window.AXIOM_GLOSSARY = [
  // ---------------- Arithmetic ----------------
  { term: 'digit', group: 'Arithmetic',
    def: 'One of the ten symbols 0 through 9 used to write numbers. A number is built by stringing digits together.',
    where: 'Every number you read; "the number 304 has three digits."' },
  { term: 'place value', group: 'Arithmetic',
    def: 'The value a digit has because of its position in a number. In 304 the 3 means 3 hundreds, not just 3.',
    where: 'Reading large numbers, lining up columns to add, and decimals.',
    source: { label: 'Khan Academy: Place value', url: 'https://www.khanacademy.org/math/arithmetic/arith-place-value' } },
  { term: 'factor', group: 'Arithmetic',
    def: 'A whole number that divides evenly into another with no remainder. The factors of 12 are 1, 2, 3, 4, 6, and 12.',
    where: 'Breaking numbers apart, simplifying fractions, and factoring in algebra.',
    aliases: ['divisor'] },
  { term: 'multiple', group: 'Arithmetic',
    def: 'The result of multiplying a number by a whole number. The multiples of 4 are 4, 8, 12, 16, and so on.',
    where: 'Times tables, finding common denominators, and skip-counting.' },
  { term: 'prime', group: 'Arithmetic',
    def: 'A whole number greater than 1 whose only factors are 1 and itself, like 2, 3, 5, 7, and 11.',
    where: 'Prime factorization and the building blocks of every whole number.',
    aliases: ['prime number'],
    source: { label: 'Wikipedia: Prime number', url: 'https://en.wikipedia.org/wiki/Prime_number' } },
  { term: 'GCD', group: 'Arithmetic',
    def: 'The greatest common divisor: the largest number that divides two (or more) numbers evenly. The GCD of 12 and 18 is 6.',
    where: 'Reducing a fraction to lowest terms; factoring out a common factor.',
    aliases: ['gcf', 'greatest common factor', 'greatest common divisor'],
    source: { label: 'Wikipedia: Greatest common divisor', url: 'https://en.wikipedia.org/wiki/Greatest_common_divisor' } },
  { term: 'LCM', group: 'Arithmetic',
    def: 'The least common multiple: the smallest number that two (or more) numbers both divide into. The LCM of 4 and 6 is 12.',
    where: 'Finding a common denominator to add or compare fractions.',
    aliases: ['least common multiple', 'lowest common multiple'],
    source: { label: 'Wikipedia: Least common multiple', url: 'https://en.wikipedia.org/wiki/Least_common_multiple' } },
  { term: 'remainder', group: 'Arithmetic',
    def: 'What is left over when one whole number does not divide evenly into another. $17 \\div 5$ gives 3 with a remainder of 2.',
    where: 'Long division and any "does it divide evenly?" question.' },
  { term: 'integer', group: 'Arithmetic',
    def: 'A whole number, including zero and negatives: ..., -2, -1, 0, 1, 2, ... but no fractions or decimals.',
    where: 'Counting, temperatures below zero, number lines.',
    source: { label: 'Wikipedia: Integer', url: 'https://en.wikipedia.org/wiki/Integer' } },
  { term: 'rational number', group: 'Arithmetic',
    def: 'Any number you can write as a fraction $\\frac{a}{b}$ of two integers (with $b \\ne 0$), such as $\\frac{3}{4}$, $5$, or $-0.25$.',
    where: 'Fractions, terminating and repeating decimals.',
    aliases: ['rational'],
    source: { label: 'Wikipedia: Rational number', url: 'https://en.wikipedia.org/wiki/Rational_number' } },
  { term: 'absolute value', group: 'Arithmetic',
    def: 'The distance of a number from zero, always non-negative. Both $5$ and $-5$ have absolute value $5$, written $|{-5}| = 5$.',
    where: 'Number lines, distances, and ignoring a sign.' },

  // ---------------- Fractions & Ratio ----------------
  { term: 'numerator', group: 'Fractions & Ratio',
    def: 'The top number of a fraction; it counts how many equal parts you have.',
    where: 'Top of a fraction; in $\\frac{3}{4}$ the numerator is 3.' },
  { term: 'denominator', group: 'Fractions & Ratio',
    def: 'The bottom number of a fraction; it tells you how many equal parts the whole is split into.',
    where: 'Bottom of a fraction; in $\\frac{3}{4}$ the denominator is 4.' },
  { term: 'reciprocal', group: 'Fractions & Ratio',
    def: 'The fraction you get by flipping a number upside down; a number times its reciprocal equals 1. The reciprocal of $\\frac{2}{3}$ is $\\frac{3}{2}$.',
    where: 'Dividing by a fraction means multiplying by its reciprocal.',
    aliases: ['multiplicative inverse'] },
  { term: 'ratio', group: 'Fractions & Ratio',
    def: 'A comparison of two quantities by division, telling you how much of one there is for each amount of the other, written $3:2$ or $\\frac{3}{2}$.',
    where: 'Recipes, mixing paint, "3 boys for every 2 girls."',
    source: { label: 'Khan Academy: Ratios', url: 'https://www.khanacademy.org/math/pre-algebra/pre-algebra-ratios-rates' } },
  { term: 'proportion', group: 'Fractions & Ratio',
    def: 'A statement that two ratios are equal, like $\\frac{2}{3} = \\frac{4}{6}$. You solve them by cross-multiplying.',
    where: 'Scaling recipes, map distances, and "if x then y" problems.' },
  { term: 'percent', group: 'Fractions & Ratio',
    def: 'A fraction out of 100. "Percent" literally means "per hundred," so $25\\%$ means $\\frac{25}{100} = 0.25$.',
    where: 'Discounts, test scores, tips, and interest rates.',
    aliases: ['percentage'] },
  { term: 'equivalent fractions', group: 'Fractions & Ratio',
    def: 'Different-looking fractions that represent the same amount, like $\\frac{1}{2}$, $\\frac{2}{4}$, and $\\frac{3}{6}$.',
    where: 'Simplifying fractions and finding common denominators.' },

  // ---------------- Algebra ----------------
  { term: 'variable', group: 'Algebra',
    def: 'A letter or symbol that stands for a number you do not yet know or that can change, like $x$ or $t$.',
    where: 'Every equation and formula; "solve for $x$."',
    source: { label: 'Khan Academy: Intro to variables', url: 'https://www.khanacademy.org/math/algebra/x2f8bb11595b61c86:foundation-algebra' } },
  { term: 'coefficient', group: 'Algebra',
    def: 'The number multiplied by a variable in a term. In $5x$ the coefficient is 5.',
    where: 'Reading and combining terms; the slope in $y = mx + b$.' },
  { term: 'term', group: 'Algebra',
    def: 'A single piece of an expression separated by plus or minus signs. In $3x + 2y - 7$ there are three terms.',
    where: 'Combining like terms; reading any expression.' },
  { term: 'expression', group: 'Algebra',
    def: 'A combination of numbers, variables, and operations with no equals sign, like $3x + 2$. You simplify or evaluate it, but you do not "solve" it.',
    where: 'Anything you can plug numbers into; the left or right side of an equation.' },
  { term: 'equation', group: 'Algebra',
    def: 'A statement that two expressions are equal, joined by an equals sign, like $2x + 1 = 7$. You solve it to find the variable.',
    where: 'Solving for an unknown; balancing both sides.' },
  { term: 'function', group: 'Algebra',
    def: 'A rule that takes each input and gives exactly one output, like a machine. Written $f(x)$, so $f(x) = x^2$ sends 3 to 9.',
    where: 'Graphs, formulas, and "for every input, one output."',
    source: { label: 'Wikipedia: Function (mathematics)', url: 'https://en.wikipedia.org/wiki/Function_(mathematics)' } },
  { term: 'slope', group: 'Algebra',
    def: 'How steep a line is: the change in $y$ divided by the change in $x$ (rise over run). In $y = mx + b$ the slope is $m$.',
    where: 'Straight-line graphs, rates, and "how fast is it climbing?"',
    aliases: ['gradient'] },
  { term: 'quadratic', group: 'Algebra',
    def: 'An expression or equation where the highest power of the variable is 2, like $x^2 + 3x - 4$. Its graph is a U-shaped parabola.',
    where: 'Factoring, the quadratic formula, and projectile paths.',
    aliases: ['quadratic equation'] },
  { term: 'polynomial', group: 'Algebra',
    def: 'An expression made of terms with whole-number powers of a variable added together, like $4x^3 - 2x + 7$.',
    where: 'Factoring, expanding, and graphing curves.',
    source: { label: 'Wikipedia: Polynomial', url: 'https://en.wikipedia.org/wiki/Polynomial' } },
  { term: 'exponent', group: 'Algebra',
    def: 'A small raised number showing how many times to multiply a base by itself. In $2^3$ the exponent is 3, so $2^3 = 2 \\times 2 \\times 2 = 8$.',
    where: 'Powers, growth, and scientific notation.',
    aliases: ['power', 'index'] },

  // ---------------- Geometry & Trig ----------------
  { term: 'vertex', group: 'Geometry & Trig',
    def: 'A corner point where two or more edges or lines meet, such as the corner of a triangle or the tip of a parabola.',
    where: 'Corners of shapes; the turning point of a parabola.',
    aliases: ['vertices'] },
  { term: 'hypotenuse', group: 'Geometry & Trig',
    def: 'The longest side of a right triangle, always opposite the right angle.',
    where: 'The Pythagorean theorem and right-triangle trig.',
    source: { label: 'Wikipedia: Hypotenuse', url: 'https://en.wikipedia.org/wiki/Hypotenuse' } },
  { term: 'radian', group: 'Geometry & Trig',
    def: 'A natural unit for measuring angles based on the radius. A full circle is $2\\pi$ radians, so $180^\\circ = \\pi$ radians.',
    where: 'The unit circle, trigonometry, and calculus.',
    source: { label: 'Wikipedia: Radian', url: 'https://en.wikipedia.org/wiki/Radian' } },
  { term: 'sine', group: 'Geometry & Trig',
    def: 'In a right triangle, the ratio of the side opposite an angle to the hypotenuse, written $\\sin\\theta$.',
    where: 'SOH-CAH-TOA, the unit circle, and waves.',
    aliases: ['sin'] },
  { term: 'cosine', group: 'Geometry & Trig',
    def: 'In a right triangle, the ratio of the side adjacent to an angle to the hypotenuse, written $\\cos\\theta$.',
    where: 'SOH-CAH-TOA, the unit circle, and waves.',
    aliases: ['cos'] },
  { term: 'tangent', group: 'Geometry & Trig',
    def: 'In a right triangle, the ratio of the opposite side to the adjacent side, written $\\tan\\theta = \\frac{\\sin\\theta}{\\cos\\theta}$. (It also names a line that just touches a curve.)',
    where: 'SOH-CAH-TOA, slopes of curves, and "a line touching a circle."',
    aliases: ['tan'] },
  { term: 'area', group: 'Geometry & Trig',
    def: 'The amount of flat space inside a shape, measured in square units. A rectangle has area length times width.',
    where: 'Floors, fields, and "how much surface?"' },
  { term: 'perimeter', group: 'Geometry & Trig',
    def: 'The total distance around the outside edge of a shape; add up all the side lengths.',
    where: 'Fencing a yard, framing a picture, "how far around?"',
    aliases: ['circumference'] },

  // ---------------- Calculus ----------------
  { term: 'limit', group: 'Calculus',
    def: 'The value a function gets closer and closer to as its input approaches some point, written $\\lim_{x\\to a} f(x)$.',
    where: 'The foundation under derivatives and integrals.',
    source: { label: 'Wikipedia: Limit of a function', url: 'https://en.wikipedia.org/wiki/Limit_of_a_function' } },
  { term: 'derivative', group: 'Calculus',
    def: 'The instantaneous rate of change of a function, or the slope of its graph at a single point, written $\\frac{dy}{dx}$ or $f\'(x)$.',
    where: 'Speed from position, slopes of curves, optimization.',
    aliases: ['differentiation'],
    source: { label: '3Blue1Brown: Essence of calculus', url: 'https://www.youtube.com/watch?v=WUvTyaaNkzM' } },
  { term: 'integral', group: 'Calculus',
    def: 'The accumulated total of a quantity, found as the area under a curve, written $\\int f(x)\\,dx$. It is the reverse of a derivative.',
    where: 'Total distance from speed, areas, and accumulation.',
    aliases: ['integration', 'antiderivative'],
    source: { label: 'Wikipedia: Integral', url: 'https://en.wikipedia.org/wiki/Integral' } },
  { term: 'rate of change', group: 'Calculus',
    def: 'How fast one quantity changes compared with another. Average rate of change is rise over run; the instantaneous version is the derivative.',
    where: 'Speed, growth rates, and slopes.' },

  // ---------------- Logic & Proof ----------------
  { term: 'theorem', group: 'Logic & Proof',
    def: 'An important mathematical statement that has been proven true from axioms and earlier results.',
    where: 'Named results like the Pythagorean theorem.' },
  { term: 'lemma', group: 'Logic & Proof',
    def: 'A smaller proven result used as a stepping stone toward proving a bigger theorem.',
    where: 'The helper facts inside a longer proof.' },
  { term: 'axiom', group: 'Logic & Proof',
    def: 'A basic statement accepted as true without proof, used as a starting point to build everything else.',
    where: 'The bedrock assumptions of a math system; the app is named after this idea.',
    aliases: ['postulate'],
    source: { label: 'Wikipedia: Axiom', url: 'https://en.wikipedia.org/wiki/Axiom' } },
  { term: 'conjecture', group: 'Logic & Proof',
    def: 'A statement believed to be true based on evidence but not yet proven.',
    where: 'Open problems like the Goldbach conjecture.' },
  { term: 'if and only if', group: 'Logic & Proof',
    def: 'A two-way logical connection: each statement is true exactly when the other is, written $\\Leftrightarrow$. To prove it you must prove both directions.',
    where: 'Definitions and biconditional theorems.',
    aliases: ['iff', 'biconditional'] },
  { term: 'contrapositive', group: 'Logic & Proof',
    def: 'The statement "if not B, then not A," formed from "if A, then B." It is always logically equivalent to the original.',
    where: 'Proofs where flipping and negating is easier than the direct approach.',
    source: { label: 'Wikipedia: Contraposition', url: 'https://en.wikipedia.org/wiki/Contraposition' } },
  { term: 'induction', group: 'Logic & Proof',
    def: 'A proof method: show a statement holds for the first case, then show that whenever it holds for one case it holds for the next, so it holds for all.',
    where: 'Proving formulas true for every whole number.',
    aliases: ['mathematical induction'],
    source: { label: 'Wikipedia: Mathematical induction', url: 'https://en.wikipedia.org/wiki/Mathematical_induction' } },
  { term: 'contradiction', group: 'Logic & Proof',
    def: 'A proof method where you assume the opposite of what you want, then derive an impossibility, forcing your original claim to be true.',
    where: 'Classic proofs like "$\\sqrt{2}$ is irrational."',
    aliases: ['proof by contradiction', 'reductio ad absurdum'] },
  { term: 'QED', group: 'Logic & Proof',
    def: 'A mark placed at the end of a proof to signal it is complete; short for the Latin "quod erat demonstrandum" ("which was to be shown").',
    where: 'The end of a written proof, often shown as a small square.',
    aliases: ['quod erat demonstrandum'] },
  { term: 'WLOG', group: 'Logic & Proof',
    def: 'Short for "without loss of generality": a phrase saying you may assume a convenient special case because the other cases work the same way.',
    where: 'Proofs where symmetry lets you handle one case to cover all.',
    aliases: ['without loss of generality'] },

  // ---------------- Estimation & Cognition ----------------
  { term: 'order of magnitude', group: 'Estimation & Cognition',
    def: 'A rough size class measured in powers of ten. Two numbers are the same order of magnitude if their ratio is under about 10; "an order of magnitude bigger" means roughly 10 times larger.',
    where: 'Quick sanity checks and comparing very different sizes.',
    source: { label: 'Wikipedia: Order of magnitude', url: 'https://en.wikipedia.org/wiki/Order_of_magnitude' } },
  { term: 'significant figures', group: 'Estimation & Cognition',
    def: 'The digits in a number that actually carry meaningful precision. 0.00420 has three significant figures.',
    where: 'Reporting measurements without faking accuracy.',
    aliases: ['sig figs', 'significant digits'] },
  { term: 'Fermi estimate', group: 'Estimation & Cognition',
    def: 'A quick, rough calculation that gets you within an order of magnitude by breaking a hard question into easy-to-guess pieces.',
    where: 'Back-of-the-envelope questions like "how many piano tuners are in Chicago?"',
    aliases: ['Fermi problem', 'back-of-the-envelope'],
    source: { label: 'Wikipedia: Fermi problem', url: 'https://en.wikipedia.org/wiki/Fermi_problem' } },
  { term: 'working memory', group: 'Estimation & Cognition',
    def: 'The small mental scratchpad that holds the few pieces of information you are actively juggling. It is limited, so offload steps onto paper.',
    where: 'Why multi-step mental math feels hard; why writing steps down helps.',
    source: { label: 'Wikipedia: Working memory', url: 'https://en.wikipedia.org/wiki/Working_memory' } },
  { term: 'deliberate practice', group: 'Estimation & Cognition',
    def: 'Focused practice aimed just beyond your current ability, with full attention and immediate feedback on what went wrong, rather than mindless repetition.',
    where: 'How you actually improve at problem-solving, not just put in time.',
    aliases: ['purposeful practice'],
    source: { label: 'Ericsson & Pool, Peak; Make It Stick (Brown, Roediger, McDaniel)', url: 'https://www.retrievalpractice.org/' } },
  { term: 'spaced repetition', group: 'Estimation & Cognition',
    def: 'Reviewing material at growing intervals over time, which strengthens long-term memory far more than cramming it all at once.',
    where: 'Smart flashcard schedules and durable studying.',
    aliases: ['spacing effect', 'distributed practice'],
    source: { label: 'Make It Stick (Brown, Roediger, McDaniel)', url: 'https://www.retrievalpractice.org/' } },
  { term: 'number sense', group: 'Estimation & Cognition',
    def: 'An intuitive feel for how big numbers are and how they relate, letting you estimate and catch nonsense answers without grinding the arithmetic.',
    where: 'Spotting that an answer is "way too big" before checking it carefully.',
    source: { label: 'Stanislas Dehaene, The Number Sense', url: 'https://en.wikipedia.org/wiki/The_Number_Sense' } }
];
